#!/usr/bin/env bash
# scripts/write-env-config.sh — the final step of installation: records
# RESOLVED ABSOLUTE values into the gitignored scripts/env.local.conf,
# so every sbatch job reads a fixed, already-resolved config instead of
# re-deriving `$HOME`-relative paths inside its own (possibly different)
# environment instance. See scripts/lib/env_config.sh for the consumer
# side and the full rationale.
#
# Usage:
#   scripts/write-env-config.sh \
#       --env-prefix      /abs/path/to/micromamba/envs/heRegistration \
#       [--micromamba-bin /abs/path/to/micromamba] \
#       [--bftools-root   /abs/path/to/extracted/glencoe/zips] \
#       [--libblosc-dir   /abs/path/to/env/with/blosc/lib]
#
# --env-prefix must already exist (this script records, it does not
# create, the environment — run `micromamba env create -n heRegistration
# -f environments/heRegistration.yml` first, then resolve its prefix via
# `micromamba env list`). --micromamba-bin auto-detects via
# `command -v micromamba` if not passed. --bftools-root / --libblosc-dir
# are OPTIONAL — only needed if you plan to convert .vsi inputs via
# scripts/submit_vsi_to_ometiff.sh and bioformats2raw/raw2ometiff/
# libblosc aren't already installed inside --env-prefix (see
# docs/install.md "VSI-input prerequisites").

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
OUT="$SCRIPT_DIR/env.local.conf"

ENV_PREFIX=""
MICROMAMBA_BIN=""
BFTOOLS_ROOT=""
LIBBLOSC_DIR=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --env-prefix)      ENV_PREFIX="$2"; shift 2 ;;
        --micromamba-bin)  MICROMAMBA_BIN="$2"; shift 2 ;;
        --bftools-root)    BFTOOLS_ROOT="$2"; shift 2 ;;
        --libblosc-dir)    LIBBLOSC_DIR="$2"; shift 2 ;;
        -h|--help)
            sed -n '2,22p' "$0"; exit 0 ;;
        *)
            echo "error: unknown argument: $1" >&2; exit 2 ;;
    esac
done

: "${ENV_PREFIX:?--env-prefix is required (absolute path to the micromamba env PREFIX)}"

if [[ ! -d "$ENV_PREFIX" ]]; then
    echo "error: --env-prefix does not exist: $ENV_PREFIX" >&2
    echo "       Create it first: micromamba env create -n heRegistration -f environments/heRegistration.yml" >&2
    echo "       then resolve its prefix with: micromamba env list" >&2
    exit 3
fi
ENV_PREFIX=$(cd "$ENV_PREFIX" && pwd)   # canonicalize to an absolute path

if [[ -z "$MICROMAMBA_BIN" ]]; then
    if ! MICROMAMBA_BIN=$(command -v micromamba); then
        echo "error: micromamba not found on PATH and --micromamba-bin not given." >&2
        exit 4
    fi
fi
if [[ ! -x "$MICROMAMBA_BIN" ]]; then
    echo "error: --micromamba-bin is not executable: $MICROMAMBA_BIN" >&2
    exit 4
fi
# Canonicalize (command -v can return a relative-looking path on some shells).
MICROMAMBA_BIN=$(cd "$(dirname "$MICROMAMBA_BIN")" && pwd)/$(basename "$MICROMAMBA_BIN")

if [[ -n "$BFTOOLS_ROOT" ]]; then
    if [[ ! -d "$BFTOOLS_ROOT" ]]; then
        echo "error: --bftools-root does not exist: $BFTOOLS_ROOT" >&2
        exit 3
    fi
    BFTOOLS_ROOT=$(cd "$BFTOOLS_ROOT" && pwd)
fi

if [[ -n "$LIBBLOSC_DIR" ]]; then
    if [[ ! -d "$LIBBLOSC_DIR" ]]; then
        echo "error: --libblosc-dir does not exist: $LIBBLOSC_DIR" >&2
        exit 3
    fi
    LIBBLOSC_DIR=$(cd "$LIBBLOSC_DIR" && pwd)
fi

{
    echo "# Generated by scripts/write-env-config.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "# Machine-local, gitignored — resolved ABSOLUTE values for THIS install."
    echo "# Do not hand-edit; re-run scripts/write-env-config.sh instead."
    echo "MICROMAMBA_BIN=$MICROMAMBA_BIN"
    echo "HEREG_ENV_PREFIX=$ENV_PREFIX"
    [[ -n "$BFTOOLS_ROOT" ]] && echo "BFTOOLS_ROOT=$BFTOOLS_ROOT"
    [[ -n "$LIBBLOSC_DIR" ]] && echo "LIBBLOSC_DIR=$LIBBLOSC_DIR"
} > "$OUT"

echo "[write-env-config] wrote $OUT:"
sed 's/^/[write-env-config]   /' "$OUT"
echo "[write-env-config] verify with: scripts/env-preflight.sh"
